
package fr.treeptik.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AdministrateurServiceImplService", targetNamespace = "http://service.treeptik.fr/", wsdlLocation = "http://localhost:8080/Eval_ws/AdministrateurServiceImpl?wsdl")
public class AdministrateurServiceImplService
    extends Service
{

    private final static URL ADMINISTRATEURSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ADMINISTRATEURSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ADMINISTRATEURSERVICEIMPLSERVICE_QNAME = new QName("http://service.treeptik.fr/", "AdministrateurServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/Eval_ws/AdministrateurServiceImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADMINISTRATEURSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ADMINISTRATEURSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AdministrateurServiceImplService() {
        super(__getWsdlLocation(), ADMINISTRATEURSERVICEIMPLSERVICE_QNAME);
    }

    public AdministrateurServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADMINISTRATEURSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdministrateurServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ADMINISTRATEURSERVICEIMPLSERVICE_QNAME);
    }

    public AdministrateurServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADMINISTRATEURSERVICEIMPLSERVICE_QNAME, features);
    }

    public AdministrateurServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrateurServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AdministrateurServiceImpl
     */
    @WebEndpoint(name = "AdministrateurServiceImplPort")
    public AdministrateurServiceImpl getAdministrateurServiceImplPort() {
        return super.getPort(new QName("http://service.treeptik.fr/", "AdministrateurServiceImplPort"), AdministrateurServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrateurServiceImpl
     */
    @WebEndpoint(name = "AdministrateurServiceImplPort")
    public AdministrateurServiceImpl getAdministrateurServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.treeptik.fr/", "AdministrateurServiceImplPort"), AdministrateurServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ADMINISTRATEURSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ADMINISTRATEURSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ADMINISTRATEURSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
