
package fr.treeptik.ws;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import fr.treeptik.pojo.Administrateur;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AdministrateurServiceImpl", targetNamespace = "http://service.treeptik.fr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AdministrateurServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns fr.treeptik.ws.Administrateur
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.DeleteResponse")
    public Administrateur delete(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<fr.treeptik.ws.Administrateur>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.FindAllResponse")
    public List<Administrateur> findAll();

    /**
     * 
     * @param administrateur
     * @return
     *     returns fr.treeptik.ws.Administrateur
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://service.treeptik.fr/", className = "fr.treeptik.ws.CreateResponse")
    public Administrateur create(
        @WebParam(name = "arg0", targetNamespace = "")
        Administrateur administrateur);

}
